server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  application:
    name: roomschedulerapi
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

api:
  security:
      token:
        secret: ${AUTHENTICATION_SECRET}
