services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schedule_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-container
    environment:
      REDIS_PASSWORD: root
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "root"]

volumes:
  db_data:
